### PR TITLE
Separate Standard and Chess960 Books

### PR DESCRIPTION
**Pull request by TheYoBots**
Previously to add a book for chess960, it had to be added in the 'standard' section. With this change there's a separate section for standard and chess960 opening books.

### CODE REVIEW

**Comment by TheYoBots** [comment]
I'm not really sure as to how I should go about fixing flake8 errors, but a possible fix could be this:
```py
variant = "chess960" if board.chess960 else str(board.uci_variant)
```
and in the `config.yml` I could change `standard` to `chess` which honestly isn't too confusing right?

**Comment by AttackingOrDefending** [comment]
The solution you proposed would require adding additional code for backwards compatibility. Another not so clean way to fix this is:
```python
if board.chess960:
    variant = "chess960"
else:
    variant = str(board.uci_variant).replace("chess", "standard")
```
In the code that you currently have, line 690 should change to `variant = str(board.uci_variant)`.

**Comment by TheYoBots** [comment]
What about this:
```py
if board.chess960:
    variant = "chess960"
else:
    variant = "standard" if board.uci_variant == "chess" else str(board.uci_variant)
```
Though I don't know if it would pass the flake8 test... I'm not sure how it works.

**Comment by TheYoBots** [comment]
I fixed all the merge conflicts. Is there any other change that I should make?

**Review by AttackingOrDefending — APPROVED** [review]

**Review by MarkZH — APPROVED** [review]

**Pull request merged**
