### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by AttackingOrDefending**
## Type of pull request:
- [ ] Bug fix
- [ ] Feature
- [x] Other

## Description:

The structure was based on [stockfish](https://github.com/official-stockfish/Stockfish/blob/master/README.md).

I can also create a new project (e.g. called `lichess-bot-images`) and upload the icon there, so the link would be more readable (would change from `https://repository-images.githubusercontent.com/129721834/49e3e215-c2bc-4116-a5da-f7ed44b3cb9b` to `https://github.com/lichess-bot-devs/lichess-bot-images/icon.png`). Right now, I am using the link for the social preview image.

## Related Issues:

None.

## Checklist:

- [x] I have read and followed the [contribution guidelines](/docs/CONTRIBUTING.md).
- [x] I have added necessary documentation (if applicable).
- [x] The changes pass all existing tests.

### CODE REVIEW

**Comment by AttackingOrDefending** [comment]
@MarkZH Do you think it having the image in a different project will be better?

**Comment by MarkZH** [comment]
Looks good. I would reduce the bottom margin of the image so there isn't so much space between the knight and the title. I think the image location is fine where it is. I don't think we'll be modifying it very often.

**Comment by AttackingOrDefending** [comment]
I can't find a way to crop the image using html in the markdown file and I don't want to change the social preview image, because GitHub suggests that social preview images have a margin of at least 40px so that they are displayed corrcectly.

**Comment by MarkZH** [comment]
Creating an new repository for images is probably best. The current URL has a decent change of breaking if GitHub ever changes its backend.

**Review by MarkZH — APPROVED** [review]

**Pull request merged**
