### PR TITLE
Add docker image for ARM

### LINKED ISSUE #988: Provide ARM Docker images
**Is your feature request related to a problem? Please describe.**
Can't run lichess-bot container in an ARM linux machine

**Describe the solution you'd like**
Build the image for both AMD and ARM

**Describe alternatives you've considered**

**Additional context**
Linux ARM machines are more and more common nowadays in cloud providers.
There are tools that take care of building both AMD and ARM images using GH actions.

### PR DESCRIPTION
**Pull request by eduherminio**
## Type of pull request:
- [ ] Bug fix
- [x] Feature
- [ ] Other

## Description:

This change should be enough to cross-compile to both AMD and ARM.
It's complex for me to set up all the tokens and registries in my fork to test it though, so let's come up with a testing strategy.
I've been doing this successfully in [my BOT's repo](https://github.com/lynx-chess/Lynx_BOT/blob/f841d54bfa73dbdc4ed4ad0ab2ad116b89f9502a/.github/workflows/docker-publish.yml#L149-L151)

## Related Issues:

Closes #988 

## Checklist:

- [x] I have read and followed the [contribution guidelines](/docs/CONTRIBUTING.md).
- [ ] I have added necessary documentation (if applicable).
- [ ] The changes pass all existing tests.

### CODE REVIEW

**Comment by AttackingOrDefending** [comment]
We can run the workflow in a branch and create a docker with a special name (e.g. `lichess-bot-devs/lichess-bot:arm`). Would that be enough for you to test it?

**Comment by eduherminio** [comment]
> We can run the workflow in a branch and create a docker with a special name (e.g. `lichess-bot-devs/lichess-bot:arm`). Would that be enough for you to test it?

Sure, something like that sounds great, I have both amd and arm linux vms available so I should be able to compare both versions from the same branch. Feel free to mingle with this branch to add the required name changes to ensure images aren't confused with the master ones.

**Comment by AttackingOrDefending** [comment]
The workflow failed (see the run [here](https://github.com/lichess-bot-devs/lichess-bot/actions/runs/9691393186/job/26742787608)). If you can't fix the multi-platform build (I don't know how hard it is to fix), then creating different dockers for amd and arm seems fine.

**Comment by eduherminio** [comment]
Can you try again @AttackingOrDefending? I added two missing steps to prepare the multi-platform build.

**Comment by AttackingOrDefending** [comment]
Done. They were created and uploaded to GHCR and docker hub.

**Comment by eduherminio** [comment]
The one tagged with `arm` works for me!

image

There's only one change I had to make, because originally I got this error about the version: harcoding a numeric version in https://github.com/lichess-bot-devs/lichess-bot/blob/6aff6a96ffe5bc25b801c8aa967a8d819cb0a2bd/lichess-bot.py#L1191

But that has to do with your change in [versioning.yml](https://github.com/lichess-bot-devs/lichess-bot/compare/master...arm#diff-8f973e2576018c50f287ed76f4fbc4d1afd1802211ccb122ae9728028cd112b3) to test, so I'd say all good!

```python
[06/28/24 14:47:29] INFO     Engine configuration OK         lichess-bot.py:1149
                    ERROR    Quitting lichess-bot due to an  lichess-bot.py:1212
                             error:
                             Traceback (most recent call
                             last):
                               File
                             "/lichess-bot/lichess-bot.py",
                             line 1209, in <module>
                                 start_lichess_bot()
                               File
                             "/lichess-bot/lichess-bot.py",
                             line 1152, in start_lichess_bot
                                 check_python_version()
                               File
                             "/lichess-bot/lichess-bot.py",
                             line 1191, in
                             check_python_version
                                 this_lichess_bot_version =
                             version_numeric(__version__)

                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/lichess-bot/lichess-bot.py",
                             line 1174, in version_numeric
                                 return [int(n) for n in
                             version_str.split(".")]
                                         ^^^^^^
                             ValueError: invalid literal for
                             int() with base 10: 'arm'
```

**Review by AttackingOrDefending — APPROVED** [review]

**Review by MarkZH — APPROVED** [review]

**Pull request merged**
